-- MySQL Script generated by MySQL Workbench
-- Fri Jul  5 10:46:25 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`hc_medicamentos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`hc_medicamentos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`hc_medicamentos` (
  `id_medicamento` INT NOT NULL AUTO_INCREMENT,
  `nombre_medicamento` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_medicamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`hc_tipo_documento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`hc_tipo_documento` ;

CREATE TABLE IF NOT EXISTS `mydb`.`hc_tipo_documento` (
  `id_tipo_documento` INT NOT NULL AUTO_INCREMENT,
  `nombre_documento` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_tipo_documento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`hc_sexo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`hc_sexo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`hc_sexo` (
  `id_sexo` INT NOT NULL AUTO_INCREMENT,
  `nombre_sexo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_sexo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`hc_estado_civil`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`hc_estado_civil` ;

CREATE TABLE IF NOT EXISTS `mydb`.`hc_estado_civil` (
  `id_estado_civil` INT NOT NULL AUTO_INCREMENT,
  `nombre_estado_civil` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_estado_civil`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`hc_pais`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`hc_pais` ;

CREATE TABLE IF NOT EXISTS `mydb`.`hc_pais` (
  `id_pais` INT NOT NULL AUTO_INCREMENT,
  `nombre_pais` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_pais`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`hc_departamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`hc_departamento` ;

CREATE TABLE IF NOT EXISTS `mydb`.`hc_departamento` (
  `id_departamento` INT NOT NULL AUTO_INCREMENT,
  `nombre_departamento` VARCHAR(45) NOT NULL,
  `id_pais` INT NOT NULL,
  PRIMARY KEY (`id_departamento`),
  INDEX `fk_hc_departamento_hc_pais1_idx` (`id_pais` ASC) VISIBLE,
  CONSTRAINT `fk_hc_departamento_hc_pais1`
    FOREIGN KEY (`id_pais`)
    REFERENCES `mydb`.`hc_pais` (`id_pais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`hc_ciudad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`hc_ciudad` ;

CREATE TABLE IF NOT EXISTS `mydb`.`hc_ciudad` (
  `id_ciudad` INT NOT NULL AUTO_INCREMENT,
  `nombre_ciudad` VARCHAR(45) NOT NULL,
  `id_departamento` INT NOT NULL,
  PRIMARY KEY (`id_ciudad`),
  INDEX `fk_hc_ciudad_hc_departamento1_idx` (`id_departamento` ASC) VISIBLE,
  CONSTRAINT `fk_hc_ciudad_hc_departamento1`
    FOREIGN KEY (`id_departamento`)
    REFERENCES `mydb`.`hc_departamento` (`id_departamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`hc_direccion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`hc_direccion` ;

CREATE TABLE IF NOT EXISTS `mydb`.`hc_direccion` (
  `id_direccion` INT NOT NULL AUTO_INCREMENT,
  `info_direccion` VARCHAR(250) NOT NULL,
  `id_ciudad` INT NOT NULL,
  PRIMARY KEY (`id_direccion`),
  INDEX `fk_hc_direccion_hc_ciudad1_idx` (`id_ciudad` ASC) VISIBLE,
  CONSTRAINT `fk_hc_direccion_hc_ciudad1`
    FOREIGN KEY (`id_ciudad`)
    REFERENCES `mydb`.`hc_ciudad` (`id_ciudad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`hc_usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`hc_usuarios` ;

CREATE TABLE IF NOT EXISTS `mydb`.`hc_usuarios` (
  `hc_usuarios` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NOT NULL COMMENT 'de alta o de baja.',
  `apellidos` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `id_tipo_documento` INT NOT NULL,
  `numero_documento` VARCHAR(45) NOT NULL,
  `id_sexo` INT NOT NULL,
  `id_estado_civil` INT NOT NULL,
  `fecha_nacimiento` VARCHAR(45) NOT NULL,
  `profesion` VARCHAR(45) NULL,
  `conyugue` VARCHAR(45) NULL,
  `tel_casa` VARCHAR(45) NULL,
  `celular` VARCHAR(45) NULL,
  `lugar_trabajo` VARCHAR(45) NULL,
  `id_direccion` INT NOT NULL,
  PRIMARY KEY (`hc_usuarios`),
  INDEX `fk_hc_usuarios_ch_tipo_documento1_idx` (`id_tipo_documento` ASC) VISIBLE,
  INDEX `fk_hc_usuarios_hc_sexo1_idx` (`id_sexo` ASC) VISIBLE,
  INDEX `fk_hc_usuarios_hc_estado_civil1_idx` (`id_estado_civil` ASC) VISIBLE,
  INDEX `fk_hc_usuarios_hc_direccion1_idx` (`id_direccion` ASC) VISIBLE,
  CONSTRAINT `fk_hc_usuarios_ch_tipo_documento1`
    FOREIGN KEY (`id_tipo_documento`)
    REFERENCES `mydb`.`hc_tipo_documento` (`id_tipo_documento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_hc_usuarios_hc_sexo1`
    FOREIGN KEY (`id_sexo`)
    REFERENCES `mydb`.`hc_sexo` (`id_sexo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_hc_usuarios_hc_estado_civil1`
    FOREIGN KEY (`id_estado_civil`)
    REFERENCES `mydb`.`hc_estado_civil` (`id_estado_civil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_hc_usuarios_hc_direccion1`
    FOREIGN KEY (`id_direccion`)
    REFERENCES `mydb`.`hc_direccion` (`id_direccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`hc_parentezco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`hc_parentezco` ;

CREATE TABLE IF NOT EXISTS `mydb`.`hc_parentezco` (
  `id_parentezco` INT NOT NULL AUTO_INCREMENT,
  `valor_parentezco` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_parentezco`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`hc_contacto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`hc_contacto` ;

CREATE TABLE IF NOT EXISTS `mydb`.`hc_contacto` (
  `id_contacto` INT NOT NULL AUTO_INCREMENT COMMENT 'contacto de paciente.',
  `nombre_contacto` VARCHAR(45) NULL,
  `apellido_contacto` VARCHAR(45) NULL,
  `telefono_1` VARCHAR(45) NULL,
  `telefono_2` VARCHAR(45) NULL,
  `id_parentezco` INT NOT NULL,
  PRIMARY KEY (`id_contacto`),
  INDEX `fk_hc_contacto_parentezco1_idx` (`id_parentezco` ASC) VISIBLE,
  CONSTRAINT `fk_hc_contacto_parentezco1`
    FOREIGN KEY (`id_parentezco`)
    REFERENCES `mydb`.`hc_parentezco` (`id_parentezco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`hc_pacientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`hc_pacientes` ;

CREATE TABLE IF NOT EXISTS `mydb`.`hc_pacientes` (
  `id_paciente` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `num_expediente` VARCHAR(45) NOT NULL,
  `id_contacto` INT NOT NULL,
  PRIMARY KEY (`id_paciente`),
  INDEX `fk_hc_pacientes_hc_usuarios1_idx` (`id_usuario` ASC) VISIBLE,
  INDEX `fk_hc_pacientes_hc_contacto1_idx` (`id_contacto` ASC) VISIBLE,
  CONSTRAINT `fk_hc_pacientes_hc_usuarios1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `mydb`.`hc_usuarios` (`hc_usuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_hc_pacientes_hc_contacto1`
    FOREIGN KEY (`id_contacto`)
    REFERENCES `mydb`.`hc_contacto` (`id_contacto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`hc_medicos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`hc_medicos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`hc_medicos` (
  `id_medico` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `identificacion_medica` VARCHAR(45) NOT NULL COMMENT 'numero de acreditacion del doctor.',
  PRIMARY KEY (`id_medico`),
  INDEX `fk_hc_medicos_hc_usuarios1_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_hc_medicos_hc_usuarios1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `mydb`.`hc_usuarios` (`hc_usuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`hc_diagnosticos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`hc_diagnosticos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`hc_diagnosticos` (
  `id_diagnostico` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(500) NOT NULL,
  `titulo` VARCHAR(45) NOT NULL COMMENT 'nombre de la enfermedad que padece el paciente',
  `fecha` DATETIME NOT NULL,
  `id_paciente` INT NOT NULL,
  `id_medico` INT NOT NULL,
  PRIMARY KEY (`id_diagnostico`),
  INDEX `fk_hc_diagnosticos_hc_usuarios_idx` (`id_paciente` ASC) VISIBLE,
  INDEX `fk_hc_diagnosticos_hc_medicos1_idx` (`id_medico` ASC) VISIBLE,
  CONSTRAINT `fk_hc_diagnosticos_hc_usuarios`
    FOREIGN KEY (`id_paciente`)
    REFERENCES `mydb`.`hc_pacientes` (`id_paciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_hc_diagnosticos_hc_medicos1`
    FOREIGN KEY (`id_medico`)
    REFERENCES `mydb`.`hc_medicos` (`id_medico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`hc_recetas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`hc_recetas` ;

CREATE TABLE IF NOT EXISTS `mydb`.`hc_recetas` (
  `id_receta` INT NOT NULL AUTO_INCREMENT,
  `id_diagnostico` INT NOT NULL,
  `fecha_emision` DATETIME NOT NULL,
  PRIMARY KEY (`id_receta`),
  INDEX `fk_hc_recetas_hc_diagnosticos1_idx` (`id_diagnostico` ASC) VISIBLE,
  CONSTRAINT `fk_hc_recetas_hc_diagnosticos1`
    FOREIGN KEY (`id_diagnostico`)
    REFERENCES `mydb`.`hc_diagnosticos` (`id_diagnostico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`hc_citas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`hc_citas` ;

CREATE TABLE IF NOT EXISTS `mydb`.`hc_citas` (
  `id_cita` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NULL,
  `descripcion` VARCHAR(500) NULL,
  `fecha_cita` VARCHAR(45) NULL,
  `fecha_creacion` VARCHAR(45) NULL,
  `id_paciente` INT NOT NULL,
  `id_medico` INT NOT NULL,
  PRIMARY KEY (`id_cita`),
  INDEX `fk_hc_citas_hc_pacientes1_idx` (`id_paciente` ASC) VISIBLE,
  INDEX `fk_hc_citas_hc_medicos1_idx` (`id_medico` ASC) VISIBLE,
  CONSTRAINT `fk_hc_citas_hc_pacientes1`
    FOREIGN KEY (`id_paciente`)
    REFERENCES `mydb`.`hc_pacientes` (`id_paciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_hc_citas_hc_medicos1`
    FOREIGN KEY (`id_medico`)
    REFERENCES `mydb`.`hc_medicos` (`id_medico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`hc_med_recetas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`hc_med_recetas` ;

CREATE TABLE IF NOT EXISTS `mydb`.`hc_med_recetas` (
  `id_medicamento` INT NOT NULL,
  `id_receta` INT NOT NULL,
  `id_med_recetas` INT NOT NULL AUTO_INCREMENT,
  `indicaciones` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`id_med_recetas`),
  INDEX `fk_hc_medicamentos_has_hc_recetas_hc_recetas1_idx` (`id_receta` ASC) VISIBLE,
  INDEX `fk_hc_medicamentos_has_hc_recetas_hc_medicamentos1_idx` (`id_medicamento` ASC) VISIBLE,
  CONSTRAINT `fk_hc_medicamentos_has_hc_recetas_hc_medicamentos1`
    FOREIGN KEY (`id_medicamento`)
    REFERENCES `mydb`.`hc_medicamentos` (`id_medicamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_hc_medicamentos_has_hc_recetas_hc_recetas1`
    FOREIGN KEY (`id_receta`)
    REFERENCES `mydb`.`hc_recetas` (`id_receta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`hc_roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`hc_roles` ;

CREATE TABLE IF NOT EXISTS `mydb`.`hc_roles` (
  `id_rol` INT NOT NULL AUTO_INCREMENT,
  `nombre_rol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_rol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`hc_usuarios_roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`hc_usuarios_roles` ;

CREATE TABLE IF NOT EXISTS `mydb`.`hc_usuarios_roles` (
  `id_usuario` INT NOT NULL,
  `id_rol` INT NOT NULL,
  INDEX `fk_hc_usuarios_has_hc_roles_hc_roles1_idx` (`id_rol` ASC) VISIBLE,
  INDEX `fk_hc_usuarios_has_hc_roles_hc_usuarios1_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_hc_usuarios_has_hc_roles_hc_usuarios1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `mydb`.`hc_usuarios` (`hc_usuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_hc_usuarios_has_hc_roles_hc_roles1`
    FOREIGN KEY (`id_rol`)
    REFERENCES `mydb`.`hc_roles` (`id_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
